In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("iller_koordinat.csv", sep=";")

In [27]:
il = "Adana"

In [28]:
df.head()

               il     lat     lon    pot
0           Adana  37.000  35.321  1.055
1        Adıyaman  37.765  38.279  1.110
2  Afyonkarahisar  38.751  30.557  1.110
3            Ağrı  39.627  43.022  1.110
4         Aksaray  38.369  34.037  1.110

In [29]:
lat = df["lat"][df["il"]==il]
lat

0    37.0
Name: lat, dtype: float64

In [30]:
potansiyel = df["pot"][df["il"]==il]
float(potansiyel)

1.055

In [31]:
df["il"].to_list()

['Adana',
 'Adıyaman',
 'Afyonkarahisar',
 'Ağrı',
 'Aksaray',
 'Amasya',
 'Ankara',
 'Antalya',
 'Ardahan',
 'Artvin',
 'Aydın',
 'Balıkesir',
 'Bartın',
 'Batman',
 'Bayburt',
 'Bilecik',
 'Bingöl',
 'Bitlis',
 'Bolu',
 'Burdur',
 'Bursa',
 'Çanakkale',
 'Çankırı',
 'Çorum',
 'Denizli',
 'Diyarbakır',
 'Düzce',
 'Edirne',
 'Elazığ',
 'Erzincan',
 'Erzurum',
 'Eskişehir',
 'Gaziantep',
 'Giresun',
 'Gümüşhane',
 'Hakkari',
 'Hatay',
 'Iğdır',
 'Isparta',
 'İstanbul',
 'İzmir',
 'Kahramanmaraş',
 'Karabük',
 'Karaman',
 'Kars',
 'Kastamonu',
 'Kayseri',
 'Kırıkkale',
 'Kırklareli',
 'Kırşehir',
 'Kilis',
 'Kocaeli',
 'Konya',
 'Kütahya',
 'Malatya',
 'Manisa',
 'Mardin',
 'Mersin',
 'Muğla',
 'Muş',
 'Nevşehir',
 'Niğde',
 'Ordu',
 'Osmaniye',
 'Rize',
 'Sakarya',
 'Samsun',
 'Siirt',
 'Sinop',
 'Sivas',
 'Şanlıurfa',
 'Şırnak',
 'Tekirdağ',
 'Tokat',
 'Trabzon',
 'Tunceli',
 'Uşak',
 'Van',
 'Yalova',
 'Yozgat',
 'Zonguldak']

In [32]:
2,2 * 3

(2, 6)

In [33]:
ready = pd.read_csv("ready.csv")
ready["dt_obj"] = pd.to_datetime(ready["dt_obj"])
ready["Generation"][25560:26303] = ready["Generation"][17544:18286]

C:\Users\talha\AppData\Local\Temp\ipykernel_6460\4168714582.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ready["Generation"][25560:26303] = ready["Generation"][17544:18286]

In [34]:
ready["month"] = ready["dt_obj"].dt.month

In [43]:
aylik = ready.groupby(ready["dt_obj"][ready["month"] == 5].dt.day).sum().reset_index()

In [44]:
aylik["dt_obj"]

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
12    13.0
13    14.0
14    15.0
15    16.0
16    17.0
17    18.0
18    19.0
19    20.0
20    21.0
21    22.0
22    23.0
23    24.0
24    25.0
25    26.0
26    27.0
27    28.0
28    29.0
29    30.0
30    31.0
Name: dt_obj, dtype: float64

In [36]:
ready[ready["month"]==5]

,dt_obj,Generation,year,hour,AirTemperature,ComfortTemperature,RelativeHumidity,week,WWCode,sun_alt_angle,...,EffectiveCloudCover7,RelativeHumidity7,ComfortTemperature7,AirTemperature7,WWCode7,WindDirection_sin1,WindDirection_cos1,WindSpeed_sin_component,WindSpeed_cos_component,month
2878,2019-05-01 00:00:00,0.000000,2019,0,16.8,15.9,36.7,18,-100.0,-34.157369,...,0.0,61.9,11.9,12.2,-100.0,0.00000,1.000000,0.000000,0.000000,5
2879,2019-05-01 01:00:00,0.000000,2019,1,15.2,14.6,45.9,18,-100.0,-35.069832,...,0.0,48.8,15.8,16.1,-100.0,0.00000,1.000000,0.000000,0.000000,5
2880,2019-05-01 02:00:00,0.000000,2019,2,15.0,14.4,46.8,18,-100.0,-32.496276,...,1.0,38.5,16.9,17.6,0.0,0.00000,1.000000,0.000000,0.000000,5
2881,2019-05-01 03:00:00,0.000000,2019,3,14.5,14.0,48.6,18,-100.0,-26.872858,...,2.5,35.7,17.9,18.7,-100.0,0.00000,1.000000,0.000000,0.000000,5
2882,2019-05-01 04:00:00,0.000000,2019,4,14.3,13.8,48.9,18,-100.0,-18.944423,...,5.0,36.8,19.1,19.7,-100.0,0.34202,-0.939693,0.171010,-0.469846,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21161,2021-05-31 19:00:00,17.110309,2021,19,20.2,20.4,44.8,22,95.0,11.499085,...,2.0,71.0,15.1,14.6,2.0,0.50000,0.866025,1.050000,1.818653,5
21162,2021-05-31 20:00:00,0.221353,2021,20,19.2,19.6,49.9,22,95.0,1.281538,...,2.0,72.0,15.1,14.6,2.0,0.34202,0.939693,0.718242,1.973355,5
21163,2021-05-31 21:00:00,0.000000,2021,21,18.3,18.5,50.0,22,4.0,-8.644969,...,2.0,72.9,15.0,14.5,2.0,0.34202,0.939693,0.513030,1.409539,5
21164,2021-05-31 22:00:00,0.000000,2021,22,17.6,17.7,51.9,22,25.0,-16.905026,...,2.0,74.8,14.3,13.8,2.0,0.50000,0.866025,0.250000,0.433013,5
21165,2021-05-31 23:00:00,0.000000,2021,23,16.8,17.0,55.0,22,3.0,-23.252532,...,6.6,76.8,14.0,13.5,80.0,0.34202,0.939693,0.342020,0.939693,5

In [37]:
type(ready["month"][1])

numpy.int64

In [48]:
def cevir(sehir_ad,lat,lon):
    import requests
    import calendar
    from datetime import datetime
    import pandas as pd
    date = datetime.now()
    end_unix_time = calendar.timegm(date.utctimetuple())
    start_unix_time = end_unix_time - 600000

    start_unix_time,end_unix_time

    date_now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    date_now

    end_unix_time = str(end_unix_time)
    start_unix_time = str(start_unix_time)

    URL = "https://pro.openweathermap.org/data/2.5/forecast/hourly?q="+sehir_ad+"&appid=96510cf05767bf32f4b4163803254243&lang=tr&units=metric"
    URL2 = "http://history.openweathermap.org/data/2.5/history/city?lat="+str(lat)+"&lon="+str(lon)+"&type=hour&start="+start_unix_time+"&end="+end_unix_time+"&units=metric&appid=96510cf05767bf32f4b4163803254243"


    r = requests.get(url = URL)
    r2 = requests.get(url = URL2)

    data_now = r.json()
    data_hist = r2.json()

    data_date = pd.json_normalize(data_now)
    data_now["list"][0]["weather"]
    w_desc = []
    w_main = []
    w_icon = []
    w_date = []

    for i in range(len(data_now["list"])):
       w_desc.append(data_now["list"][i]["weather"][0]["description"])
       w_main.append(data_now["list"][i]["weather"][0]["main"])
       w_icon.append(data_now["list"][i]["weather"][0]["icon"])
       w_date.append(data_now["list"][i]["dt_txt"])

    icon_df = pd.DataFrame(w_icon)
    icon_df = icon_df.rename(columns={0:"icon"})
    icon_df["main"] = w_main
    icon_df["desc"] = w_desc
    icon_df["date"] = w_date

    icon_df

    data_hist["list"][0]["weather"]
    wh_desc = []
    wh_main = []
    wh_icon = []
    wh_date = []

    for i in range(len(data_hist["list"])):
      wh_main.append(data_hist["list"][i]["weather"][0]["main"])
      wh_desc.append(data_hist["list"][i]["weather"][0]["description"])
      wh_icon.append(data_hist["list"][i]["weather"][0]["icon"])
      wh_date.append(data_hist["list"][i]["dt"])

    iconh_df = pd.DataFrame(wh_icon)
    iconh_df = iconh_df.rename(columns={0:"icon"})
    iconh_df["desc"] = wh_desc
    iconh_df["main"] = wh_main
    iconh_df["date"] = wh_date


    for i in range(len(iconh_df)):
      iconh_df["date"][i] = datetime.utcfromtimestamp(iconh_df["date"][i])

    iconh_df["date"] = pd.to_datetime(iconh_df["date"])
    iconh_df.date = iconh_df["date"].dt.tz_localize("utc").dt.tz_convert('Asia/Istanbul')
    iconh_df['date'] = iconh_df['date'].dt.strftime('%Y-%m-%d %H:%M:%S')
    iconh_df

    icono_df = pd.concat([iconh_df, icon_df]).reset_index()
    icono_df["date"] = pd.to_datetime(icono_df["date"])
    icono_df["day"] = pd.to_datetime(icono_df.date).dt.day_name()


    return icono_df

In [46]:
lat = 39.925533
lon = 32.8543

In [49]:
cevir("Ankara",lat,lon)

C:\Users\talha\AppData\Local\Temp\ipykernel_6460\1855157787.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iconh_df["date"][i] = datetime.utcfromtimestamp(iconh_df["date"][i])

     index icon             desc    main                date        day
0        0  04n    broken clouds  Clouds 2022-05-03 21:00:00    Tuesday
1        1  04n  overcast clouds  Clouds 2022-05-03 22:00:00    Tuesday
2        2  10n       light rain    Rain 2022-05-03 23:00:00    Tuesday
3        3  04n    broken clouds  Clouds 2022-05-04 00:00:00  Wednesday
4        4  04n  overcast clouds  Clouds 2022-05-04 01:00:00  Wednesday
..     ...  ...              ...     ...                 ...        ...
255     91  02d       az bulutlu  Clouds 2022-05-14 09:00:00   Saturday
256     92  02d       az bulutlu  Clouds 2022-05-14 10:00:00   Saturday
257     93  02d       az bulutlu  Clouds 2022-05-14 11:00:00   Saturday
258     94  02d       az bulutlu  Clouds 2022-05-14 12:00:00   Saturday
259     95  04d  parçalı bulutlu  Clouds 2022-05-14 13:00:00   Saturday

[260 rows x 6 columns]

In [12]:
import pandas as pd
import numpy as np
from PIL import Image
import weather
from pandas.api.types import CategoricalDtype
import re 
import datetime
import icon_data
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import locale
from datetime import datetime as dt2
import awesome_streamlit as ast
ready = pd.read_csv("ready.csv")

In [14]:
ready["dt_obj"] = pd.to_datetime(ready["dt_obj"])
ready["month"] = ready["dt_obj"].dt.month
aylikort = ready.groupby(ready["dt_obj"][ready["month"]==4].dt2.day).mean().reset_index()
aylikort

AttributeError: Can only use .dt accessor with datetimelike values